import { FC } from "react";
import { Content } from "@prismicio/client"; // for getting the autogenerated type from slice machine 
import { PrismicRichText, SliceComponentProps } from "@prismicio/react";
import { PrismicNextImage, PrismicNextLink } from "@prismicio/next";

/**
 * Props for `Hero`.
 */
export type HeroProps = SliceComponentProps<Content.HeroSlice>;

/**
 * Component for "Hero" Slices.
 */
const Hero: FC<HeroProps> = ({ slice }) => {
  return (
    <section
      data-slice-type={slice.slice_type}
      data-slice-variation={slice.variation}
    >
   <PrismicRichText field={slice.primary.heading}
    components={{
       heading1:({children}) => <h1 className="text-7xl font-bold leading-tight tracking-tight 
        text-slate-700 font-nunito-sans">{children}</h1>
    }} />
    <PrismicRichText field={slice.primary.body}
       components={{
        paragraph:({children})=> <p className="text-2xl font-normal leading-10 text-slate-600 mb-4 
         text-center md:mb-6 ">{children}</p>
       }} />
    <PrismicNextLink field={slice.primary.button_link}>
       {slice.primary.button_text}
    </PrismicNextLink>
    <PrismicNextImage field={slice.primary.image} />
    </section>
  );
};

export default Hero;
