import type { Metadata } from "next";
import { Nunito, Nunito_Sans , Sono} from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  display:'swap'
});

const sono = Sono({
  variable: "--font-sono",
  subsets: ["latin"],
  display:'swap'
});
const nunito_sans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  display:"swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"   className={clsx(nunito.variable, nunito_sans.variable,sono.variable, "antialiased "
  )}>
     <body>
        {children}
      </body>
    </html>
  );
}
